config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :rooms, only: %i[ show ] do
    resources :messages, shallow: true, only: %i[ create edit update destroy show ]
  end

  post 'join', to: 'user_session#create'
  delete '/logout', to: 'user_session#destroy'

  root 'user_session#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :room

  broadcasts_to :room

  validates :author, :room, :content, presence: true

  def edited?
    created_at != updated_at
  end
end

app/models/room.rb
class Room < ApplicationRecord
  DEFAULT_NAME = 'general'.freeze

  has_many :messages

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  class << self
    def default_room
      Room.find_or_create_by!(name: DEFAULT_NAME)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages, foreign_key: :author_id
  validates :name, presence: true, uniqueness: { case_sensitive: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :authenticate_user

  private

    def current_user
      @current_user ||= User.find_by(id: session[:current_user_id]) if session[:current_user_id]
    end
    helper_method :current_user

    def authenticate_user
      redirect_to root_url unless current_user
    end


  def user_not_authorized
    head :forbidden
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[ create ]
  before_action :set_message, only: %i[ update edit destroy show ]
  before_action :authorize_message, except: %i[ create ]

  def create
    @message = @room.messages.new(message_params)
    @message.author = current_user

    if @message.save
      Bot::RespondToCommandJob.set(wait: 1.second).perform_later(@message)

      render turbo_stream: turbo_stream.append(:messages, @message)
    else
      render 'new', layout: false, status: :unprocessable_entity
    end
  end

  def update
    if @message.update(message_params)
      render @message
    else
      render 'edit', layout: false, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    @message.destroy
  end

  def show
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def authorize_message
    authorize @message
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show ]

  def show
    @messages = @room.messages
      .includes(:author)
      .limit(100)
      .order(created_at: :desc)
      .reverse

    @new_message = Message.new(room: @room)
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end
end

app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
  skip_before_action :authenticate_user, only: %i[ new create destroy ]

  def new
    redirect_to Room.default_room if current_user
  end

  def create
    user = User.find_or_create_by(user_session_params)
    if user.persisted?
      session[:current_user_id] = user.id

      room = Room.default_room
      Bot::GreetUserJob.set(wait: 2.seconds).perform_later(user, room)

      redirect_to room
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    session.delete(:current_user_id)
    redirect_to root_url
  end

  private

  def user_session_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/message_helper.rb
module MessageHelper
  def format_message_content(content)
    HtmlFormatter.call(content)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireChat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-current-user-id="<%= current_user&.id %>">
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with model: message.persisted? ? message : [message.room, message], data: { controller: 'form', action: 'turbo:submit-end->form#resetForm' } do |f| %>
  <%= f.text_field :content, class: 'form-control', required: true, autocomplete: 'off', autofocus: true, placeholder: "Message ##{message.room.name}" %>

  <% if message.persisted? %>
    <div class='pt-2'>
      <%= link_to 'Cancel', @message, class: 'btn btn-sm btn-outline-secondary' %>
      <%= f.submit 'Save changes', class: 'btn btn-sm btn-primary'%>
    <div>
  <% end %>
<% end %>

app/views/messages/_message.html.erb
<%= turbo_frame_tag dom_id(message), class: 'pb-1 px-3',
    data: { controller: 'message', action: 'mouseout->message#toggleActions mouseover->message#toggleActions', 'message-author-id-value': message.author_id } do %>
  <div class='row row-cols-auto gx-2'>
    <div class='col fw-bold'>
      <%= h message.author.name %>
    </div>
    <div class='col'>
      <%= local_time message.created_at, format: :short, class: 'fw-light fs-7' %>
    </div>
    <% if message.edited? %>
      <div class='col'>
        <span class='fw-light fs-7'>edited <%= local_time message.updated_at, format: :short %></span>
      </div>
    <% end %>
    <div class='col invisible' data-message-target='actions'>
      <%= link_to 'edit', edit_message_path(message), class: 'fs-7 link-secondary' %>
      <%= link_to 'delete', message_path(message), method: :delete, class: 'fs-7 link-secondary' %>
    </div>
  </div>

  <div class='formatted-content'>
    <%= format_message_content message.content  %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<%= turbo_frame_tag dom_id(@message) do %>
  <div data-controller='scroll-into-view' class='py-2'>
    <%= render 'form', message: @message %>
  </div>
<% end %>

app/views/messages/new.html.erb
<%= turbo_frame_tag @message do %>
  <%= render 'messages/form', message: @message %>
<% end %>

app/views/messages/show.html.erb
<%= render @message %>

app/views/rooms/show.html.erb
<%= turbo_stream_from @room %>

<div class='d-flex flex-column h-100'>
  <div class='flex-shrink-0 d-flex align-items-center mb-2 bg-purple'>
    <h1 class='flex-grow-1 m-0 p-2 h3 text-center text-white-50'>#<%= h @room.name %></h1>
    <%= link_to 'Logout', logout_path, method: :delete, class: 'p-2 text-white-50 text-decoration-none' %>
  </div>
  
  <div class='flex-grow-1 d-flex flex-column overflow-auto message-list' id='messages'
      data-controller='message-list' data-action='resize@window->message-list#scrollToBottom'>
    <%= render partial: 'messages/message', collection: @messages, cached: true %>
  </div>

  <%= turbo_frame_tag @new_message, class: 'flex-shrink-0 px-3 pb-3 pt-2' do %>
    <%= render 'messages/form', message: @new_message %>
  <% end %>
</div>

app/views/user_session/new.html.erb
<div class='d-flex align-items-center h-100'>
  <%= form_with model: User.new, url: join_path, class: 'w-galaxy mw-100 m-auto p-3 d-grid gap-3', data: { controller: 'form' } do |f| %>
    <h1 class='h3 text-center'>Hotwire Chat</h1>
    <%= f.text_field :name, class: 'form-control form-control-lg', placeholder: 'Enter your name', required: true, autofocus: true, autocomplete: 'off' %>
    <%= f.submit 'Join chat', class: 'btn btn-primary btn-lg w-100' %>
  <% end %>
</div>